### ISSUE TITLE
suggestion: "recently added" folder or folder sorted by core release date

### ISSUE THREAD

**Issue by liljordo** [Toryalai1/MiSTer_ArcadeDatabase#11]
Apologies if this has been suggested before (or should have been suggested elsewhere); it would be extremely useful if there was a folder under Collections that listed the X most recently released arcade cores, or a Collection that lists the same cores as the primary list but in reverse chronological order of release on MiSTer. 

Currently one must seek out information regarding new core releases from any number of decentralized sources, or must visually parse Update_All quickly enough to spot new arcade cores as they're added. Additionally, the number of released arcade cores has grown so enormously that it can be difficult to know if a core is new, or simply one the user doesn't remember. It would be very useful to have a dedicated place within the Arcade Organizer framework to check for new releases and/or to see how long a core has been available. 

Thanks for reading and for all the work you do maintaining this extremely useful and necessary tool!

**Comment by Toryalai1** [comment]
Hi,
Good suggestion, but this should instead be raised here: https://github.com/theypsilon/_arcade-organizer/issues

**Comment by liljordo** [comment]
Thanks for pointing me in the right direction!
