### ISSUE TITLE
Screen Orientation Errors

### ISSUE THREAD

**Issue by NFGman** [Toryalai1/MiSTer_ArcadeDatabase#17]
A whole pile of the games are incorrectly categorized WRT vert CW or CCW orientation.  

I've gone through every title, and if it was marked CW or CCW, and couldn't be changed to match that orientation, I've indicated it below.  The CW list was more accurate than the CCW list, which was full of errors.

As requested, titles are marked by their ROM names.

Games that should not be in CW:

1943
afighter
mrjong
legiono
crazyblk
freeze
jack
mplanets
qbert
sonicbom
timescan
zzyzzyxx

Some of the above games appear to have rotation options but they don't work.

Games that should not be in CCW:

combh
perfrman
tigerh

A huge number of games not listed in CW **can be**.  All of the following games, listed **only** in CCW, have CW rotation options and so fit both categories:

galivan
airduel
alcon
arkanoid2
centiped
cosmica
devzone
extrmatn
imgfight
magspot
Mikie
nomnlnd
roadf
slapfigh
panic
truxton2
dangar
wndrplnt

There are probagly a ton of games that are only in CW, but work both ways, but I haven't gone through the lists that way yet.

**Comment by Toryalai1** [comment]
Done
