### ISSUE TITLE
Horizontal title incorrect

### ISSUE THREAD

**Issue by mrchrisster** [Toryalai1/MiSTer_ArcadeDatabase#3]
I noticed `/media/fat/_Arcade/_Organized/_4 Video & Inputs/_2 Rotation/_Horizontal/Air Duel (Japan, M72 hardware).mra` is not a horizontal game

**Comment by Toryalai1** [comment]
Hi
Thanks for the heads up. I'll fix it in the next release

**Comment by Toryalai1** [comment]
This is now done.

**Comment by mrchrisster** [comment]
Hey hey, just putting this here since it's realted to the same issue. 
I noticed Galaxian is playing with my horizontal games:
/media/fat/_Arcade/_Organized/_4 Video & Inputs/_3 Move Inputs/_2-way horizontal/Galaxian (Namco, Set 1).mra

**Comment by Toryalai1** [comment]
Thanks for the report. I'll fix it

**Comment by mrchrisster** [comment]
And one more if you don' mind:
/media/fat/_Arcade/_Organized/_3 Collections/_4 By Genre/_Shooter - Horizontal/Scooter Shooter (W).mra

**Comment by Toryalai1** [comment]
Hi, 
I just checked Galaxian and it is correct as it is. It is a 2-way horizontal input game. You can only move the ship horizontally. 

Scooter shooter should also be correct. While it is a vertical-oriented game, you move horizontally.

**Comment by mrchrisster** [comment]
Ah ok I see, that's too bad. For Super Attract Mode I filter horizontal games with a simple grep for horizontal. This means I would need to find another way to create a horizontal list. Thanks for letting me know!

**Comment by Toryalai1** [comment]
Hi,
I did a major overhaul of the category. It should now 100% follow MAME. Have a look :)

**Comment by mrchrisster** [comment]
Yeah, that's what I should do and have done in the past. I somehow thought casting a wider net might be a good idea and the folder structure changed at some point which screwed with my script... but yeah, should be an easy fix. Thanks for all your work!

**Comment by mrchrisster** [comment]
Hey hey, just noticed:
`/media/fat/_Arcade/_Organized/_4 Video & Inputs/_2 Rotation/_Horizontal/Exerion (Taito).mra`
is not a horizontal game. I have Super Attract Mode running and every now and then notice things like that, hope you don't mind ;)

**Comment by Toryalai1** [comment]
Thanks for the info. I will update it this Friday with other fixes :)

**Comment by Toryalai1** [comment]
Just pushed an update. It should be vertical (cw) now: 
![image](https://user-images.githubusercontent.com/82502378/220867901-92e880e2-f573-45c9-8b50-7801cc89f839.png)
